use_frameworks!

target 'YLSliderTabLayout_Example' do
  pod 'YLSliderTabLayout', :path => '../'

  target 'YLSliderTabLayout_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
